/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Widgets/Avatar/index.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Icon: typeof import('./src/components/Widgets/Icon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserItem: typeof import('./src/components/UserList/UserItem/index.vue')['default']
    UserList: typeof import('./src/components/UserList/index.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin/index.vue')['default']
  }
}
